[parameters]
# experiment name
exp_name = "fig_3"

# tmp directory path
tmp_dir = "default"

# sim data directory path
sim_dir = "default"

save_linelist = false
save_current_suscep = true

# number of simulation replicates
nrep = 1

# simulation max time
tmax = 6.0

# time when increased transmission occurs
t_boost_transmission = 3.0

# simulated time step size
dt = 0.005

# synthetic population size
pop_size = 5000000

# number of people initially infected
initial_infected = 0

# number of people initially recovered
initial_recovered = 0

# simulate transmission between individuals (if false, infection hazard is exogenous)
simulate_transmission = false

# probability of externally seeded inf
pr_seeded_inf = 0.0

# average infection hazard for normal years
beta = 1.0

# boosted infection hazard for larger-than-normal epidemic
beta_boosted = 5.0

# seasonal forcing amplitude multiplier
seasonality_amplifier = 1.0

# seasonal forcing shift
seasonality_shift = 0.5

# parameters controlling transition rates between SEIR compartments
# for simulations with an exogenous infection hazard and where susceptibility is
# modeled using waning infection immunity, large values are used so that people
# move back to the susceptibile compartment quickly
sigma = 1e5 # 1 / average latent period
gamma = 1e5 # 1 / average infection duration
omega = 1e5 # 1 / average immunity duration

# average baseline susceptibility
vax_mean_pre_vax_suscep = 1.0
unvax_mean_pre_vax_suscep = 1.0

# shape parameter for susceptibility gamma distribution
vax_pre_vax_suscep_shape = 2.0
unvax_pre_vax_suscep_shape = 0.2

# allow for re-infections
allow_reinf = true

# infection-derived immunity waning half life
inf_imm_halflife = 4.0

# vaccination coverage
vax_coverage = 0.5

# vaccination auto-correlation (prob being re-vaccinated)
pr_vax_to_vax = 0.85

# true vaccine efficacy
vax_efficacy = 0.5

# vaccine-derived immunity waning half life
vax_imm_halflife = 0.0 # 0 corresponds to no waning

# checkpoints to vaccinate population
vaccination_checkpoint = 1.0

# time point when vaccination starts
t_vax_start = 0.0